apiVersion: apps/v1
kind: Deployment
metadata:
  name: titan-ccp-kieker-bridge-raritan
spec:
  selector:
    matchLabels:
      app: titan-ccp-kieker-bridge-raritan
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: titan-ccp-kieker-bridge-raritan
    spec:
      containers:
      - name: titan-ccp-kieker-bridge-raritan
        image: industrialdevops/titan-ccp-kieker-bridge-raritan:20190404144022
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "bootstrap:9092"
        - name: KAFKA_TOPIC
          value: "input"