apiVersion: v1
kind: Service
metadata:  
  name: titan-ccp-kieker-bridge-raritan-outside
spec:
  type: NodePort
  selector:    
    app: titan-ccp-kieker-bridge-raritan
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31190
    protocol: TCP