apiVersion: v1
kind: Service
metadata:  
  name: titan-ccp-stats
spec:
  type: NodePort
  selector:    
    app: titan-ccp-stats
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31103
    protocol: TCP