apiVersion: apps/v1
kind: Deployment
metadata:
  name: titan-ccp-stats
spec:
  selector:
    matchLabels:
      app: titan-ccp-stats
  replicas: 1
  template:
    metadata:
      labels:
        app: titan-ccp-stats
    spec:
      containers:
      - name: titan-ccp-stats
        image: industrialdevops/titan-ccp-stats:latest
        env:
        - name: CASSANDRA_HOST
          value: "cassandra"
        - name: WEBSERVER_PORT
          value: "80"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-cp-kafka:9092"
        - name: KAFKA_TOPIC_ACTIVEPOWER
          value: "input"
        - name: KAFKA_TOPIC_AGGRACTIVEPOWER
          value: "output"
        - name: SCHEMA_REGISTRY_URL
          value: "http://kafka-cp-schema-registry:8081"