apiVersion: apps/v1
kind: Deployment
metadata:
  name: titan-ccp-aggregation
spec:
  selector:
    matchLabels:
      app: titan-ccp-aggregation
  replicas: 1
  template:
    metadata:
      labels:
        app: titan-ccp-aggregation
    spec:
      containers:
      - name: titan-ccp-aggregation
        image: industrialdevops/titan-ccp-aggregation:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-cp-kafka:9092"
        - name: EMIT_PERIOD_MS
          value: "10000"
        - name: GRACE_PERIOD_MS
          value: "10000"
        - name: SCHEMA_REGISTRY_URL
          value: "http://kafka-cp-schema-registry:8081"
        - name: COMMIT_INTERVAL_MS
          value: "100"