apiVersion: v1
kind: Service
metadata:  
  name: titan-ccp-aggregation
spec:
  type: NodePort
  selector:    
    app: titan-ccp-aggregation
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31182
    protocol: TCP