apiVersion: apps/v1
kind: Deployment
metadata:
  name: titan-ccp-raritan-simulator
spec:
  selector:
    matchLabels:
      app: titan-ccp-raritan-simulator
  replicas: 1
  template:
    metadata:
      labels:
        app: titan-ccp-raritan-simulator
    spec:
      containers:
      - name: titan-ccp-raritan-simulator
        image: industrialdevops/titan-ccp-raritan-simulator:latest
        env:
        - name: PUSH_ADDRESS
          value: "http://titan-flow-raritan-service:8080/raritan"
        - name: LOG_LEVEL
          value: "info"