apiVersion: apps/v1
kind: Deployment
metadata:
  name: titan-ccp-history
spec:
  selector:
    matchLabels:
      app: titan-ccp-history
  replicas: 1
  template:
    metadata:
      labels:
        app: titan-ccp-history
    spec:
      containers:
      - name: titan-ccp-history
        image: industrialdevops/titan-ccp-history:latest
        env:
        - name: CASSANDRA_HOST
          value: "cassandra"
        - name: WEBSERVER_PORT
          value: "80"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-cp-kafka:9092"
        - name: SCHEMA_REGISTRY_URL
          value: "http://kafka-cp-schema-registry:8081"
        - name: CASSANDRA_INIT_TIMEOUT_MS
          value: "60000"