apiVersion: apps/v1
kind: Deployment
metadata:
  name: titan-flow-raritan
spec:
  selector:
    matchLabels:
      app: titan-flow-raritan
  replicas: 1
  template:
    metadata:
      labels:
        app: titan-flow-raritan
    spec:
      containers:
      - name: titan-flow-raritan
        image: industrialdevops/flow-raritan:latest
        env:
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-cp-kafka:9092"
        - name: KAFKA_TOPIC
          value: "input"
        - name: SCHEMA_REGISTRY_URL
          value: "http://kafka-cp-schema-registry:8081"
        - name: TIMESTAMPS_IN_MS
          value: "false"