apiVersion: batch/v1
kind: Job
metadata:
  name: kafka-topic-create
spec:
  template:
    spec:
      containers:
      - name: kafka-topic-create
        image: solsson/kafka:2.1.1@sha256:8bc8242c649c395ab79d76cc83b1052e63b4efea7f83547bf11eb3ef5ea6f8e1
        volumeMounts:
          - name: setup-config-volume
            mountPath: /setup
        command: ['/bin/bash', '/setup/setup.sh']
        #command: ['echo', 'helloo']
        #command:
        #- ./bin/kafka-topics.sh
        #- --zookeeper
       # -   zookeeper:2181
        #- --create
        #- --if-not-exists
        #- --topic
        #-   input
        #- --partitions
        #-   "3"
        #- --replication-factor
        #-   "2"
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
      restartPolicy: Never
      volumes:
      - name: setup-config-volume
        configMap:
          name: kafka-setup-config