apiVersion: v1
kind: Service
metadata:  
  name: titan-ccp-frontend
spec:
  type: NodePort
  selector:    
    app: titan-ccp-frontend
  ports:  
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 31200
    protocol: TCP