version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 10.0.75.1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  cassandra:
    image: cassandra
    ports:
      - "9042:9042"
  redis:
    image: redis
    ports:
      - "6379:6379"