version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
  kafka:
    image: wurstmeister/kafka
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "input:3:1,output:3:1,configuration:3:1"
      KAFKA_LOG_RETENTION_HOURS: 1
  schema-registry:
    image: confluentinc/cp-schema-registry:5.3.1
    depends_on:
      - zookeeper
      - kafka
    expose:
      - "8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
  cassandra:
    image: cassandra
    expose:
      - "9042"
    environment:
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 128M
    mem_limit: 1024m
  redis:
    image: redis
    expose:
      - "6379"
  titan-ccp-aggregation:
    image: industrialdevops/titan-ccp-aggregation:4146ce0d30daa3ac2d5495911bf00f5b4e2b7583
    expose:
      - "80"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
  titan-ccp-history:
    image: industrialdevops/titan-ccp-history:34563eecd9123189065a8217024aa42dd84b3fd9
    expose:
      - "80"
    environment:
      CASSANDRA_HOST: cassandra
      WEBSERVER_PORT: 80
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
  titan-ccp-stats:
    image: industrialdevops/titan-ccp-stats:d1ac1923b23dd637f2a13eed3d0e7b87260fa599
    expose:
      - "80"
    environment:
      CASSANDRA_HOST: cassandra
      WEBSERVER_PORT: 80
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC_ACTIVEPOWER: input
      KAFKA_TOPIC_AGGRACTIVEPOWER: output
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
  titan-ccp-configuration:
    image: industrialdevops/titan-ccp-configuration:e062b239d98cbd33bd80f7a43046c9ad5f85ce21
    expose:
      - "80"
    environment:
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      STARTUP_WAIT_MS: 30000
      DEMO: "true"
  titan-ccp-frontend:
    image: industrialdevops/titan-ccp-frontend:c9ee49ea8835df9f86eec7ad1e33a5f479462598
    ports:
      - "8185:8080"
    environment:
      DEMO: "true"
      CONFIGURATION_BASE_URL: "http://titan-ccp-configuration:80"
      HISTORY_BASE_URL: "http://titan-ccp-history:80"
      STATS_BASE_URL: "http://titan-ccp-stats:80"
  titan-flow-raritan:
    image: industrialdevops/flow-raritan:a36500bab7a0cd9ae2106edb95f9d77c8a7eff5c
    expose:
      - "8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: input
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
      TIMESTAMPS_IN_MS: "false"
  raritan-simulator:
    image: industrialdevops/titan-ccp-raritan-simulator:20190405091811
    environment:
      KIEKER_BRIDGE_ADDRESS: http://titan-flow-raritan:8080/raritan
      LOG_LEVEL: debug
      SETUP: demo
