version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
  kafka:
    image: wurstmeister/kafka
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "input:3:1,output:3:1,configuration:3:1"
      KAFKA_LOG_RETENTION_HOURS: 1
  cassandra:
    image: cassandra
    expose:
      - "9042"
    environment:
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 128M
    mem_limit: 1024m
  redis:
    image: redis
    expose:
      - "6379"
  titan-ccp-aggregation:
    image: industrialdevops/titan-ccp-aggregation:0d0ec2d57393ee6fc6fef5dc4f06977e24c905f8
    expose:
      - "80"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  titan-ccp-history:
    image: industrialdevops/titan-ccp-history:8d9a361ba70c9de3461098d264190ed91b24318c
    expose:
      - "80"
    environment:
      CASSANDRA_HOST: cassandra
      WEBSERVER_PORT: 80
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  titan-ccp-stats:
    image: industrialdevops/titan-ccp-stats:1d8e3e7c255c5f00c7c700b727b8301acfe765b1
    expose:
      - "80"
    environment:
      CASSANDRA_HOST: cassandra
      WEBSERVER_PORT: 80
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC_ACTIVEPOWER: input
      KAFKA_TOPIC_AGGRACTIVEPOWER: output
  titan-ccp-configuration:
    image: industrialdevops/titan-ccp-configuration:a5afaadf3ebd28c31b064fd0fb5fa6ddd954e114
    expose:
      - "80"
    environment:
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      STARTUP_WAIT_MS: 30000
      DEMO: "true"
  titan-ccp-frontend:
    image: industrialdevops/titan-ccp-frontend:db2737314ff17e212253140a3b1311056042ca40
    ports:
      - "8185:8080"
    environment:
      DEMO: "true"
      CONFIGURATION_BASE_URL: "http://titan-ccp-configuration:80"
      HISTORY_BASE_URL: "http://titan-ccp-history:80"
      STATS_BASE_URL: "http://titan-ccp-stats:80"
  titan-ccp-record-bridge-raritan:
    image: industrialdevops/titan-ccp-kieker-bridge-raritan:20190404144022
    expose:
      - "8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: input
  titan-ccp-raritan-simulator:
    image: industrialdevops/titan-ccp-raritan-simulator:20190405091811
    environment:
      KIEKER_BRIDGE_ADDRESS: http://titan-ccp-record-bridge-raritan:8080/raritan
      SETUP: demo