version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
  kafka:
    image: wurstmeister/kafka
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ZOOKEEPER_CONNECTION_TIMEOUT_MS: 30000
      KAFKA_CREATE_TOPICS: "input:3:1,output:3:1,configuration:3:1,aggregation-feedback:3:1,dayofweek:3:1,hourofday:3:1,hourofweek:3:1"
      KAFKA_LOG_RETENTION_HOURS: 1
  schema-registry:
    image: confluentinc/cp-schema-registry:5.3.1
    depends_on:
      - zookeeper
      - kafka
    expose:
      - "8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper:2181'
  cassandra:
    image: cassandra
    expose:
      - "9042"
    environment:
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 128M
    mem_limit: 1024m
  mongodb:
    image: bitnami/mongodb:latest
    expose:
      - "27017"
    environment:
      MONGODB_REPLICA_SET_MODE: primary
      MONGODB_REPLICA_SET_NAME: rs0
      MONGODB_REPLICA_SET_KEY: replicaset
      MONGODB_ADVERTISED_HOSTNAME: mongodb
      MONGODB_ROOT_PASSWORD: password
  titan-ccp-aggregation:
    image: industrialdevops/titan-ccp-aggregation:60f938cf3085190f4e18ff9c671ff181276eb6c0
    expose:
      - "80"
    mem_limit: 512m
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
      EMIT_PERIOD_MS: 10000
      GRACE_PERIOD_MS: 10000
  titan-ccp-history:
    image: industrialdevops/titan-ccp-history:ed88b02a53a9ae88c6150db495c6faead84b1018
    expose:
      - "80"
    mem_limit: 512m
    environment:
      WEBSERVER_PORT: 80
      CASSANDRA_HOST: cassandra
      CASSANDRA_INIT_TIMEOUT_MS: 60000
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
  titan-ccp-stats:
    image: industrialdevops/titan-ccp-stats:3a303c6c60c9b813d68289e76c7618a48b17e679
    expose:
      - "80"
    mem_limit: 512m
    environment:
      WEBSERVER_PORT: 80
      CASSANDRA_HOST: cassandra
      CASSANDRA_INIT_TIMEOUT_MS: 60000
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC_ACTIVEPOWER: input
      KAFKA_TOPIC_AGGRACTIVEPOWER: output
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
  titan-ccp-sensor-management:
    image: industrialdevops/titan-ccp-sensor-management:4344cb28a6c60390d0df5ff6c022ba94b8a5ce9a
    expose:
      - "80"
    environment:
      MONGODB_CONNECTION_URL: mongodb://root:password@mongodb:27017/?replicaSet=rs0
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      DEMO: "true"
  titan-ccp-frontend:
    image: industrialdevops/titan-ccp-frontend:7dfc41556647edf8679d5fc461dfc3185f5b9dea
    ports:
      - "8185:80"
    environment:
      DEMO: "true"
      SENSOR_MANAGEMENT_BASE_URL: "http://titan-ccp-sensor-management:80"
      HISTORY_BASE_URL: "http://titan-ccp-history:80"
      STATS_BASE_URL: "http://titan-ccp-stats:80"
  titan-flow-raritan:
    image: industrialdevops/flow-raritan:8c7c1f8051d04c0a6c37b9ea33a49fa31be44fc7
    depends_on:
      - zookeeper
      - kafka
      - schema-registry
    expose:
      - "8080"
    mem_limit: 512m
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: input
      SCHEMA_REGISTRY_URL: http://schema-registry:8081
      TIMESTAMPS_IN_MS: "false"
  raritan-simulator:
    image: industrialdevops/titan-ccp-raritan-simulator:d7e4fde3880fee8922d836d54e6a11814736d93f
    environment:
      PUSH_ADDRESS: http://titan-flow-raritan:8080/raritan
      LOG_LEVEL: info
