version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
  kafka:
    image: wurstmeister/kafka
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "input:3:1,output:3:1"
      KAFKA_LOG_RETENTION_HOURS: 1
  cassandra:
    image: cassandra
    expose:
      - "9042"
  redis:
    image: redis
    expose:
      - "6379"
  titan-ccp-aggregation:
    image: industrialdevops/titan-ccp-aggregation:20181121083454
    expose:
      - "80"
    environment:
      CASSANDRA_HOST: cassandra
      WEBSERVER_PORT: 80
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      CONFIGURATION_HOST: titan-ccp-configuration
      CONFIGURATION_PORT: 80
  titan-ccp-kieker-bridge-raritan:
    image: industrialdevops/titan-ccp-kieker-bridge-raritan:20181121154241
    expose:
      - "8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: input
  titan-ccp-configuration:
    image: industrialdevops/titan-ccp-configuration:20181112142005
    expose:
      - "80"
    environment:
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      STARTUP_WAIT_MS: 30000
      DEMO: "true"
  titan-ccp-frontend:
    image: industrialdevops/titan-ccp-frontend:20181115145153
    ports:
      - "8185:8080"
    environment:
      DEMO: "true"
  titan-ccp-raritan-simulator:
    image: industrialdevops/titan-ccp-raritan-simulator:20180726123855
    environment:
      KIEKER_BRIDGE_ADDRESS: http://titan-ccp-kieker-bridge-raritan:8080/raritan
      SETUP: demo