version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    expose:
      - "2181"
  kafka:
    image: wurstmeister/kafka
    expose:
      - "9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "input:3:1,output:3:1,configuration:3:1"
      KAFKA_LOG_RETENTION_HOURS: 1
  cassandra:
    image: cassandra
    expose:
      - "9042"
    environment:
      MAX_HEAP_SIZE: 512M
      HEAP_NEWSIZE: 128M
    mem_limit: 1024m
  redis:
    image: redis
    expose:
      - "6379"
  titan-ccp-aggregation:
    image: industrialdevops/titan-ccp-aggregation:34179c7a389145933fa666cc62d1c5c031611d67
    expose:
      - "80"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  titan-ccp-history:
    image: industrialdevops/titan-ccp-history:719aa88c1038ab6b80d2324ff4e65b74902e6597
    expose:
      - "80"
    environment:
      CASSANDRA_HOST: cassandra
      WEBSERVER_PORT: 80
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
  titan-ccp-stats:
    image: industrialdevops/titan-ccp-stats:63ee5776b52136d0e6572fa8082aef6eb42ad709
    expose:
      - "80"
    environment:
      CASSANDRA_HOST: cassandra
      WEBSERVER_PORT: 80
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC_ACTIVEPOWER: input
      KAFKA_TOPIC_AGGRACTIVEPOWER: output
  titan-ccp-configuration:
    image: industrialdevops/titan-ccp-configuration:e062b239d98cbd33bd80f7a43046c9ad5f85ce21
    expose:
      - "80"
    environment:
      REDIS_HOST: redis
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      STARTUP_WAIT_MS: 30000
      DEMO: "true"
  titan-ccp-frontend:
    image: industrialdevops/titan-ccp-frontend:c9ee49ea8835df9f86eec7ad1e33a5f479462598
    ports:
      - "8185:8080"
    environment:
      DEMO: "true"
      CONFIGURATION_BASE_URL: "http://titan-ccp-configuration:80"
      HISTORY_BASE_URL: "http://titan-ccp-history:80"
      STATS_BASE_URL: "http://titan-ccp-stats:80"
  titan-flow-raritan:
    image: industrialdevops/flow-raritan:a36500bab7a0cd9ae2106edb95f9d77c8a7eff5c
    expose:
      - "8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC: input
      TIMESTAMPS_IN_MS: "false"
  raritan-simulator:
    image: industrialdevops/titan-ccp-raritan-simulator:20190405091811
    environment:
      KIEKER_BRIDGE_ADDRESS: http://titan-flow-raritan:8080/raritan
      LOG_LEVEL: debug
      SETUP: demo