apiVersion: v1
kind: Service
metadata:  
  name: titan-ccp-sensor-management
spec:
  type: NodePort
  selector:    
    app: titan-ccp-sensor-management
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31101
    protocol: TCP