apiVersion: apps/v1
kind: Deployment
metadata:
  name: titan-ccp-sensor-management
spec:
  selector:
    matchLabels:
      app: titan-ccp-sensor-management
  replicas: 1
  template:
    metadata:
      labels:
        app: titan-ccp-sensor-management
    spec:
      containers:
      - name: titan-ccp-sensor-management
        image: industrialdevops/titan-ccp-sensor-management:latest
        env:
        - name: WEBSERVER_PORT
          value: "80"
        - name: MONGODB_CONNECTION_URL
          value: "mongodb://root:password@mongo-mongodb:27017/?replicaSet=rs0"
        - name: KAFKA_BOOTSTRAP_SERVERS
          value: "kafka-cp-kafka:9092"
        - name: DEMO
          value: "true"