kind: Service
apiVersion: v1
metadata:
  name: kafka-outside-1
spec:
  selector:
    app: kafka
    kafka-broker-id: "1"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 31121
    nodePort: 31121
  type: NodePort