kind: Service
apiVersion: v1
metadata:
  name: kafka-outside-2
spec:
  selector:
    app: kafka
    kafka-broker-id: "2"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 31122
    nodePort: 31122
  type: NodePort