kind: Service
apiVersion: v1
metadata:
  name: kafka-outside-0
spec:
  selector:
    app: kafka
    kafka-broker-id: "0"
  ports:
  - protocol: TCP
    targetPort: 9094
    port: 31120
    nodePort: 31120
  type: NodePort