kind: Service
apiVersion: v1
metadata:
  name: cassandra-outside
spec:
  selector:
    app: cassandra
  ports:
  - protocol: TCP
    targetPort: 9042
    port: 32500
    nodePort: 32500
  type: NodePort