kind: Service
apiVersion: v1
metadata:
  name: kafka-manager-outside
spec:
  type: NodePort
  selector:
    app: kafka-manager
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30050
