apiVersion: apps/v1
kind: Deployment
metadata:
  name: titan-ccp-frontend
spec:
  selector:
    matchLabels:
      app: titan-ccp-frontend
  replicas: 1
  template:
    metadata:
      labels:
        app: titan-ccp-frontend
    spec:
      containers:
      - name: titan-ccp-frontend
        image: industrialdevops/titan-ccp-frontend:latest
        env:
        - name: VUE_APP_DEMO_MODE
          value: "false"
        - name: CONFIGURATION_BASE_URL
          value: "http://titan-ccp-sensor-management:80"
        - name: HISTORY_BASE_URL
          value: "http://titan-ccp-history:80"
        - name: STATS_BASE_URL
          value: "http://titan-ccp-stats:80"