apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: titan-ccp-frontend
spec:
  selector:
    matchLabels:
      app: titan-ccp-frontend
  replicas: 1
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: titan-ccp-frontend
    spec:
      containers:
      - name: titan-ccp-frontend
        image: industrialdevops/titan-ccp-frontend:1f021d328a6e00719a6ccb256e931b45e09d62fd
        env:
        - name: DEMO
          value: "false"
        - name: CONFIGURATION_BASE_URL
          value: "http://titan-ccp-sensor-management:80"
        - name: HISTORY_BASE_URL
          value: "http://titan-ccp-history:80"
        - name: STATS_BASE_URL
          value: "http://titan-ccp-stats:80"