apiVersion: v1
kind: Service
metadata:  
  name: titan-ccp-frontend
spec:
  type: NodePort
  selector:    
    app: titan-ccp-frontend
  ports:  
  - name: http
    port: 80
    targetPort: 80
    nodePort: 31100
    protocol: TCP